all:
	g++ -o ./bin/number -g ./bin/number.cpp
	g++ -o ./bin/removetag -g ./bin/removetag.cpp
	g++ -o ./bin/removetag0 -g ./bin/removetag0.cpp
	g++ -o ./bin/noop -g ./bin/noop.cpp
	g++ -o simple -g simple.cpp
	cp /bin/ls ./bin
	cp /bin/cat ./bin
clean:
	rm simple
